// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/jasmine-node/jasmine-node.d.ts
declare function it(expectation:string, assertion:(done:(err?:any) => void) => void, timeout?:number):void;

declare module "jasmine-node" {
    interface ExecuteSpecsOptions {
        specFolders: string[],
        onComplete?: (runner:jasmine.Runner) => void,
        isVerbose?: boolean,
        showColors?: boolean,
        teamcity?: string | boolean,
        useRequireJs?: boolean,
        regExpSpec: RegExp,
        junitreport?: {
            report: boolean,
            savePath: string,
            useDotNotation: boolean,
            consolidate: boolean
        },
        includeStackTrace?: boolean,
        growl?: boolean
    }

    interface JasmineNode {
        executeSpecsInFolder(options:ExecuteSpecsOptions): void;
        loadHelpersInFolder(path:string, pattern:RegExp): void;
    }

    var jasmine:JasmineNode;

    export = jasmine;
}
